### ISSUE TITLE
TOC not working

### ISSUE THREAD

**Issue by f-mc2** [oleeskild/obsidian-digital-garden#336] opened 2023-07-02 21:47 UTC
I updated both the plugin and the template, but I am not able to make the TOC appear. I tried using both the global notes setting, and forcing the option on single notes, but I never succeeded. 
Given it has been a while since I last published something on my digital garden (I still use Netlify to deploy everything), I thought it might have been a problem related with a "bulk update", but I do not know how to even check this possibility.

I apologize in advance if the issue is trivial and simply due to my abyssal ignorance.

**Comment by oleeskild** [comment] 2023-07-03 14:18
This should work 🤔 it could be that there is something else that is breaking the build in vercel. Can you check the Deployments tab in Vercel, and see if anything there is red instead of green?

![CleanShot 2023-07-03 at 16 16 57@2x](https://github.com/oleeskild/obsidian-digital-garden/assets/6201338/ef386767-bf47-4b23-a882-83fcc8196d5b)

**Comment by f-mc2** [comment] 2023-07-03 16:28
Thanks for the quick reply. Actually, I still use Netlify, and there are no red lines in the build/deploy log. The only line that looks weird to me is the following (bear in mind that I am completely ignorant in these matters):

The Netlify Functions setting targets a non-existing directory: netlify/functions

Do you think it's better if I start the digital garden from scratch using Vercel?

**Comment by oleeskild** [comment] 2023-07-04 10:15
Hmm, it shouldn't matter if you are using Netlify or Vercel, both should be working fine. 

Could you perhaps either make the github repo public or invite me to the repo with read-only permission? Then I can probably figure out whats going wrong more quickly :)

**Comment by f-mc2** [comment] 2023-07-04 13:37
I just invited you to the repo. Thank you very, very much for the help!

**Comment by oleeskild** [comment] 2023-07-04 15:03
No problem 😄, thanks! So I've tried to run it locally, and it seems the ToC is working as expected. Two pages does not have a TOC, "1.1 Sets and functions" and "1.4 Improper limits of scalar functions". This is because they don't have any headers, and so they don't have anything to make a ToC from. Is this the same behaviour you are seeing? Or is every page without a ToC?

Regarding the creation/update time, can you screenshot the timestamp settings, and double check if the "Created timestamp Frontmatter Key" really is empty or contains a space or similar?

**Comment by oleeskild** [comment] 2023-07-04 18:48
Seems to be working on your site as well? 
<img width="1441" alt="CleanShot 2023-07-04 at 20 46 35@2x" src="https://github.com/oleeskild/obsidian-digital-garden/assets/6201338/c16716be-0817-45f0-bdbd-869e5dcb7eaf">

ToC is not shown on mobile currently. Is that what you mean, that it doesn't show up on small screens?

**Comment by oleeskild** [comment] 2023-07-04 18:53
Also, regarding the timestamps: does your note actually have a frontmatter with dg-created defined? i.e. something like this:
```
---
dg-publish: true
dg-created: '2023-01-01'
---
```

If it doesn't, you should just leave those fields blank in the settings, and it will use data from when the file was created and updated.

**Comment by f-mc2** [comment] 2023-07-04 19:23
OK, there's something weird going one with my browsers then. I tried Chrome, Chromium, Firefox, and UnGoogled Chromium, and what I get is this:

 
![website1](https://github.com/oleeskild/obsidian-digital-garden/assets/114299723/0f783277-c1d3-4344-bd57-71c52e200ea7)

I also tried DuckDuckGo on mobile, but, following what you said, this behavior is expected.

Moreover, the graph appears on the bottom of the page:

![website2](https://github.com/oleeskild/obsidian-digital-garden/assets/114299723/d57b266a-87b4-4edd-9ba3-a84a2c48fe7b)

Finally, whenever I load a page on the browser, a black rectangle appears and disappears in a moment. It took me some time, but I managed to get a screenshot:

![website3](https://github.com/oleeskild/obsidian-digital-garden/assets/114299723/d52f7243-a398-48e7-ab84-f71a75af44f1)

I'm starting to think there's something wrong with my computer settings.

**Comment by f-mc2** [comment] 2023-07-04 19:26
> Also, regarding the timestamps: does your note actually have a frontmatter with dg-created defined? i.e. something like this:
> 
> ```
> ---
> dg-publish: true
> dg-created: '2023-01-01'
> ---
> ```
> 
> If it doesn't, you should just leave those fields blank in the settings, and it will use data from when the file was created and updated.

I did not have dg-created in the frontmatter because I thought setting global options was enough. I tried to put dg-created: *nothing* in a note, but nothing changed.

Again, I really think there's some weird stuff going on with my computer settings.

**Comment by oleeskild** [comment] 2023-07-04 19:35
The problem is these two:
![CleanShot 2023-07-04 at 21 35 10@2x](https://github.com/oleeskild/obsidian-digital-garden/assets/6201338/8237e020-a397-4afd-941a-a2ff69669883)
They should be empty

**Comment by oleeskild** [comment] 2023-07-04 19:42
> Finally, whenever I load a page on the browser, a black rectangle appears and disappears in a moment. It took me some time, but I managed to get a screenshot:

Yes, this is a known bug. It is the global graph that takes some seconds to hide. It will be fixed in a future update. 

The reason your layout is differen is simply that your screen is too small. The full layout only shows on 13" screens or bigger. If you try to zoom out you should see it

**Comment by f-mc2** [comment] 2023-07-04 20:46
> The reason your layout is differen is simply that your screen is too small. The full layout only shows on 13" screens or bigger. If you try to zoom out you should see it

I am embarrassed. My screen is 14'', but I changed the resolution...once I zoomed out everything was in place as you were saying. It really did not occur to me to zoom out, and I feel incredibly stupid for this.

I sincerely apologize for the time I stole to you without a real reason, and I thank you again for the patience and support. 

You and the other contributors are doing a great job, and this plugin is amazing!

**Comment by f-mc2** [comment] 2023-07-04 20:49
> The problem is these two: ![CleanShot 2023-07-04 at 21 35 10@2x](https://user-images.githubusercontent.com/6201338/250979766-8237e020-a397-4afd-941a-a2ff69669883.png) They should be empty

Thank you again. Putting the fields blank solved the problem for all the notes, except the Home (which is the only one having dg-pinned: true in the frontmatter). However, not having timestamps in the Home does not bother me, so I'll not bother with it.

**Comment by oleeskild** [comment] 2023-07-05 07:04
Don't worry about it, it's not obvious that the ToC needs a certain screen size to show. Some time in the future I want to add it to the smaller screen size version as well. 

The home page currently doesn't have timestamps, maybe we'll consider allowing people to enable it there as well in the future, but as a general rule, home pages are usually indexes to other content, and they tend to not have that information available. Similar to news sites.  

I'm glad it worked out!

**Closed by oleeskild** 2023-07-05 07:04 UTC
