### ISSUE TITLE
Excessive number of deployments exceeds the resources limit of the free plan

### ISSUE THREAD

**Issue by gamberoillecito** [oleeskild/obsidian-digital-garden#475] opened 2023-10-07 08:06 UTC
Last couple of days I've been setting up my digital garden and publishing multiple updates (around 15/20 per day max) but after that vercel stops accepting any new update because it says that I have exceeded the free plan limit with this error message (on the vercel website):
`Resource is limited - try again in 13 hours (more than 100, code: "api-deployments-free-per-day").`

Checking the logs I can see a very big number of deployments. (The image below doesn't show the full number of lines)
![immagine](https://github.com/oleeskild/obsidian-digital-garden/assets/42670032/1f2cf5ca-c4b8-4310-b989-ed596d3317bc)

I'm not sure whether this is a bug or not but I don't see why this should be wanted.

As I side note the obsidian plugin doesn't give any feedback about the vercel error, thus making debugging more difficult

**Comment by aniketnegi** [comment] 2023-10-08 13:21
it seems like #320 has already given a solution to the problem you're having. Have you tried that?

**Comment by gamberoillecito** [comment] 2023-10-08 18:45
@aniketnegi hi, I'm sorry I didn't see it before posting, I'll try that but I think it should work. It would be nice to have that done automatically by the plugin if possible though

**Comment by mr-nano** [comment] 2024-05-07 07:31
The suggested solution is quite complicated - is there a way to avoid the digital garden to create a commit per file, and rather chunk it?

**Comment by oleeskild** [comment] 2024-05-07 15:31
I've finally gotten around to implement this. I've released it as a Beta version for now, that can be installed via BRAT. Any feedback, either here or in the [Discord](https://discord.gg/UsPH74nEVS) is much appreciated 🙏 

[Release](https://github.com/oleeskild/obsidian-digital-garden/releases/tag/2.57.0)

I'm closing this issue, as it is a duplicate of #327

**Closed by oleeskild** 2024-05-07 15:31 UTC
